// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI.Entities
{
    [Table("Category")]
    public partial class Category
    {
        public Category()
        {
            SubCategories = new HashSet<SubCategory>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }

        [InverseProperty(nameof(SubCategory.Category))]
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}