// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI.Entities
{
    [Table("Clothing")]
    public partial class Clothing
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(100)]
        public string Size { get; set; }
        public double? Price { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        public byte[] Image { get; set; }
        [StringLength(250)]
        public string ImagePath { get; set; }
        public int? CategoryId { get; set; }
        public string UserId { get; set; }
        public int? SubCategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}