// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities;

[Table("Other")]
public partial class Other
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(250)]
    public string Title { get; set; }

    public byte[] Image { get; set; }

    [StringLength(250)]
    public string ImagePath { get; set; }

    public double? Price { get; set; }

    [StringLength(50)]
    public string Category { get; set; }

    [StringLength(250)]
    public string Description { get; set; }

    public string UserName { get; set; }
}