// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI.Entities
{
    [Table("Record")]
    public partial class Record
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(250)]
        public string Title { get; set; }
        [Column("band")]
        [StringLength(250)]
        public string Band { get; set; }
        [StringLength(100)]
        public string Album { get; set; }
        [StringLength(100)]
        public string Year { get; set; }
        [StringLength(250)]
        public string Genre { get; set; }
        public byte[] Image { get; set; }
        [StringLength(250)]
        public string ImagePath { get; set; }
        public double? Price { get; set; }
        public int? CategoryId { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        public string UserId { get; set; }
        public int? SubCategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}