// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI.Entities
{
    [Table("SubCategory")]
    public partial class SubCategory
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
        public int? CategoryId { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("SubCategories")]
        public virtual Category Category { get; set; }
    }
}